---
- hosts: webservers
  sudo: yes
  vars:
   doc_root: /var/www/html
   http_port: 80

  vars_prompt:
  - name: username
    prompt: What is your name?

  tasks:
  - name: Ensure Apache is installed
    yum: name=httpd state=present
    when: ansible_os_family == "RedHat"

  - name: Ensure Apache is running
    service: name=httpd enabled=yes state=started

  - name: Deploy configuration file
    template: src=templates/httpd.j2 dest=/etc/httpd/conf/httpd.conf
    notify:
    - Restart Apache

  - name: copy index file
    template: src=templates/index.j2 dest={{ doc_root }}/index.html

  handlers:
  - name: Restart Apache
    service: name=httpd state=restarted

- hosts: dbservers
  sudo: yes

  tasks:
  - name: Ensure MySQL is installed
    yum: name=mysql-server state=present
    when: ansible_os_family == "RedHat"

  - name: Ensure MYSQL is running
    service: name=mysqld state=started

- hosts: webservers:dbservers
  sudo: yes

  tasks:
  - name: Stop IPTABLES now!!!
    service: name=iptables state=stopped
