---
- name: Ensure Apache is installed
  yum: name=httpd state=present
  
- name: Ensure Apache is running
  service: name=httpd enabled=yes state=started

- name: Deploy configuration file
  template: src=httpd.j2 dest=/etc/httpd/conf/httpd.conf
  notify:
  - Restart Apache

- name: copy index file
  template: src=index.j2 dest={{ doc_root }}/index.html
